# Generated by Django 4.0.5 on 2022-06-26 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PP', '0007_alter_comment_likes_alter_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile-images/')),
                ('link1', models.CharField(blank=True, max_length=300, null=True)),
                ('link2', models.CharField(blank=True, max_length=300, null=True)),
                ('link3', models.CharField(blank=True, max_length=300, null=True)),
                ('link4', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PP.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PP.profile'),
        ),
    ]
