# Generated by Django 4.0.5 on 2022-06-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0008_profile_comment_profile_pic_post_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
    ]
