# Generated by Django 4.0.5 on 2022-06-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0009_remove_post_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_pic',
        ),
    ]
