# Generated by Django 4.0.5 on 2022-07-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0010_remove_comment_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
