# Generated by Django 4.0.5 on 2022-07-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0011_profile_sex_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, null=True),
        ),
    ]
