# Generated by Django 4.0.5 on 2022-07-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0012_alter_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Мужской', 'Женский')], max_length=7, null=True),
        ),
    ]
