# Generated by Django 4.0.5 on 2022-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0014_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
