# Generated by Django 4.0.5 on 2022-10-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0021_alter_postimage_image_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
