# Generated by Django 4.0.5 on 2022-10-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0022_alter_notification_options_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
